calc > try($a=2;) catch(Exception $e)($a=1)

calc > try{$a=2;} catch(Exception $e){$a=1}

